### ISSUE TITLE
Histogram Reweighting

### ISSUE THREAD

**Issue by ramess101** [GOMC-WSU/GOMC_Examples#5]
@msoroush 

In my meeting with Dr. Potoff today, we briefly discussed using MBAR with GCMC.  We need to validate that MBAR is giving the same results as histogram reweighting for the case where epsilon and sigma do not change. Unfortunately, our histogram reweighting code appears to have a bug in it. Specifically, the VLE properties we obtain have systematic deviations from the values reported in the literature.

For example, we simulated hexane using the Mie 16-6 potential with GOMC.

These are the histograms we obtained for the different chemical potentials and temperatures:

![image](https://user-images.githubusercontent.com/23408516/37679044-6f5ac056-2c45-11e8-9e36-435d4881e684.png)

As you can see here, our densities do not agree perfectly with the values reported by Potoff et al. (especially at higher T):

![image](https://user-images.githubusercontent.com/23408516/37678895-05ce225e-2c45-11e8-9bbc-7867dd26c0b2.png)

The strange thing is, that our higher temperature results get worse as we include histograms from the lower temperature simulations. For example, this is what we get at the highest temperature if we only include the histograms at the "bridge":

![image](https://user-images.githubusercontent.com/23408516/37679193-d719b90e-2c45-11e8-86c9-fcd2a20e8349.png)

This suggests that we are not weighting the histograms properly. 

Dr. Potoff thought that we could do a couple of things to resolve this issue:

1. You send me your histogram reweighting code
2. I send you my raw simulation output files for hexane and you run your code to see what results you get
3. You send me your raw simulation output for some system (he thought you should have the data for the noble gases readily available) and I use my code to see if I get the same results
4. I send you my histogram reweighting code

I think we should try options 1, 2, and 3 before we consider 4. 

If you could send me your histogram reweighting code and/or simulation output files that would be great.

Here are my hexane GOMC output files for the number of particles and energies (first row has Temperature, Chemical potential, and box dimensions) 

[hexane_GCMC_output.zip](https://github.com/GOMC-WSU/GOMC_Examples/files/1830942/hexane_GCMC_output.zip)

Thanks

**Comment by jpotoff** [comment]
Hi Richard,
Since we have your histogram data, we will start by pushing it through our analysis code and see what we get.

**Comment by jpotoff** [comment]
@ramess101 @msoroush Ok, I'm pretty sure your code is working, and the issue is the chemical potentials used to generate the histograms.  I ran your data through our code and got results that are very similar to yours.
![trho_comp](https://user-images.githubusercontent.com/13317201/37930257-3b9e3bce-3110-11e8-8960-e2323cf5b9f9.png)

Many of your low temperature runs in the liquid phase should be sampling both the liquid and vapor phases, since you are running at close to the coexistence chemical potential. 
![chem_pot](https://user-images.githubusercontent.com/13317201/37929916-3098126e-310f-11e8-8ec2-05e709abda72.png)

However, because of the large free energy barrier, the simulation is never going to tunnel between phases.  What you have is a metastable simulation, which throws the reweighting off.  I'm surprised that your results are as good as they are.  Normally one will get weird unphysical behavior in the coexistence curve in these situations.  

To account for this, we run slightly off the coexistence curve so the simulation is sampling only the liquid or vapor phase.  If you try your analysis code on the attached group of histograms you should get the same answer.  

![histograms](https://user-images.githubusercontent.com/13317201/37930000-75ba6180-310f-11e8-9eec-9b27a887a40a.png)
[histograms.zip](https://github.com/GOMC-WSU/GOMC_Examples/files/1849354/histograms.zip)

**Comment by ramess101** [comment]
@jpotoff 

OK, great, this is very reassuring. I am glad that it is our state points that are the problem and not that we have a bug in our code. Changing the chemical potential in a script is a lot faster than debugging code :+1:   

It appears that shifting the chemical potentials at lower temperatures is a subtle but very important step. Running the histograms you provided me with through our histogram reweighting code gives excellent agreement:

![image](https://user-images.githubusercontent.com/23408516/37934154-917319b2-310a-11e8-948e-2d4799f5f06f.png)

Thank you for helping resolve this issue.

By the way, just in case you might use your histogram plot in the future, the legend is not quite right. You are missing "mu = -3980, T = 480", which should correspond to the solid blue line. This explains why the cyan line does not have a label (it should correspond to the the "mu = -3625, T = 330" label). Obviously this is not important for our discussion, but I just thought we should catch it now to avoid future confusion.

**Comment by jpotoff** [comment]
@ramess101 Thanks for the catch on the histogram plot.  I've updated it with the correct labels.
